version: '3.8'

services:
  backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile
    container_name: library-backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_URL=mysql://user:password@db:3306/library
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - library_network

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: library-api
    ports:
      - "5000:5000"
    volumes:
      - ../api:/app
    environment:
      - FLASK_APP=src/run.py
      - FLASK_ENV=development
      - DATABASE_URL=mysql://user:password@db:3306/library
      - REDIS_URL=redis://redis:6379/0
      - LIBRARY_API_URL=http://backend:8000/api/v1
      - LIBRARY_AUTH_URL=http://backend:8000/api/token
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - library_network

  db:
    image: mysql:8.0
    container_name: library-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=library
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - library_network

  redis:
    image: redis:6.2-alpine
    container_name: library-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - library_network

  celery:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: library-celery
    command: celery -A config worker -l info
    volumes:
      - ../backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_URL=mysql://user:password@db:3306/library
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - library_network

networks:
  library_network:
    name: library_network
    driver: bridge

volumes:
  mysql_data:
    name: library_mysql_data
  redis_data:
    name: library_redis_data 